definitions:
  auth.GenerateAuthURLResponse:
    properties:
      url:
        type: string
    type: object
  auth.TokenResponse:
    properties:
      token:
        type: string
      token_type:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/oauth-url:
    get:
      consumes:
      - application/json
      description: Currently, the authorization is integrated with Auth0. This endpoint
        will generate an authorization URL for the client to redirect to the Auth0
        login page.
      operationId: GenerateAuthURL
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/auth.GenerateAuthURLResponse'
      summary: Generate oauth login url
      tags:
      - Auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: SignIn with oauth code
      operationId: SignIn
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/auth.TokenResponse'
      summary: SignIn with oauth code
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: SignUp with oauth code
      operationId: SignUp
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/auth.TokenResponse'
      summary: SignUp with oauth code
      tags:
      - Auth
swagger: "2.0"
