service: user-service
provider:
  name: aws
  profile: me_dev
  stage: ${opt:stage}
  region: ap-northeast-1
  runtime: provided.al2
  memorySize: 128
package:
  patterns:
    - '!*/**'
    - ./bin/main
    - ../.env
functions:
    http-proxy:
      handler: bin/main
      events:
        - httpApi: '*'
      timeout: 30
plugins:
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 11000
    websocketPort: 11001
    lambdaPort: 11002
    albPort: 11003
    useDocker: true