definitions:
  user.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  user.UserResponse:
    properties:
      user:
        $ref: '#/definitions/user.User'
    type: object
  user.UsersResponse:
    properties:
      users:
        items:
          $ref: '#/definitions/user.User'
        type: array
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      consumes:
      - application/json
      description: List users
      operationId: ListUsers
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/user.UsersResponse'
      summary: List users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create user
      operationId: CreateUser
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/user.UserResponse'
      summary: Create user
      tags:
      - User
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user
      operationId: DeleteUser
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete user
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Get user by id
      operationId: GetUser
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/user.UserResponse'
      summary: Get user by id
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Partial update user
      operationId: PartialUpdateUser
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/user.UserResponse'
      summary: Partial update user
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update user
      operationId: UpdateUser
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/user.UserResponse'
      summary: Update user
      tags:
      - User
swagger: "2.0"
